<template>
  <div id="main">
    <h2>Organisation Sign Up</h2>
    <!-- Name -->
    <input
      type="text"
      v-model="name"
      placeholder="Enter Name"
      class="text"
      required
    /><br />
    <!-- E-mail -->
    <input
      type="text"
      v-model="mail"
      placeholder="Enter E-mail"
      class="text"
      required
    /><br />
    <!-- phone -->
    <input
      type="tel"
      v-model="phone"
      placeholder="Enter Phone No"
      required
      class="text"
      pattern="[6-9]{1}[0-9]{9}"
    /><br />
    <!-- Location -->
    <input
      type="address"
      v-model="location"
      class="text"
      required
      placeholder="Enter Location"
    />
    <!-- Password -->
    <input
      type="password"
      v-model="pass"
      placeholder="Enter Password"
      required
      class="text"
    />
    <br />
    <br />
    <button id="b1" type="submit" v-on:click="signUp">Sign Up</button
    ><br /><br />Already a user? <a href="#" @click="login">Log In</a><br />
  </div>
</template>
<script>
import axios from "axios";
export default {
  name: "SignUp",
  data() {
    return {
      name: "",
      mail: "",
      pass: "",
      phone: "",
      location: "",
    };
  },

  methods: {
    // Redirect to login screen
    login() {
      this.$router.push({ name: "logIn" });
    },
    signUp() {
      // If all details are provided, then post the request to the server
      if (this.name && this.mail && this.pass && this.location && this.phone) {
        axios
          .post("http://localhost:3000/addOrganisation", {
            email: this.mail,
            name: this.name,
            password: this.pass,
            phoneNo: this.phone,
            location: this.location,
          })
          .then((response) => {
            // Checking for already existing data
            if (response.data.message === "Organisation already exists") {
              alert("Organisation Already Exists! Please Login!");
              this.$router.push({ name: "logIn" });
            }
            // Saving requisite data to local storage
            localStorage.setItem("id", response.data.id); //id of organisation as generated by MongoDB
            localStorage.setItem("token", response.data.token); // JWT token to validate every subsequent request
            localStorage.setItem("email", response.data.email);
            localStorage.setItem("name", this.name);
            localStorage.setItem("phoneNo", this.phone);
            alert("Sign Up Successful! Welcome to ManagD!");
          });
      } else {
        alert("Please fill the required details");
      }
    },
  },
  mounted() {
    let token = localStorage.getItem("token"); //check if already logged in
    if (token) {
      this.$router.push({ name: "dashBoard" });
    }
  },
};
</script>

<style scoped>
a {
  text-decoration: none;
  color: rgb(3, 66, 120);
}
a:hover {
  color: red;
}
h3 {
  margin-bottom: 0px;
}
#main {
  border: solid 1.5px rgb(59, 59, 247);
  border-radius: 10px;
  padding: 15px;
  margin: auto;
  margin-top: 50px;
  max-width: 300px;
  max-height: 600px;
  /* background: rgb(185, 203, 248); */
}
#b1 {
  width: 150px;
  background: rgb(246, 247, 252);
  color: rgba(18, 1, 255, 0.991);
  border: none;
}
#b1:hover {
  color: red;
}
.text {
  height: 40px;
  width: 250px;
  border-radius: 7px;
  border: solid 1px;
  margin: 10px;
}
</style>
